# Changes here will be overwritten by Copier
_commit: v0.16.0
_src_path: gh:appleparan/copier-modern-ml
allow_insecure_host: false
author_email: jongsukim8@gmail.com
author_fullname: Jongsu Liam Kim
ci: github
copyright_date: '2025'
copyright_holder: Jongsu Liam Kim
copyright_holder_email: jongsukim8@gmail.com
copyright_license: Apache License 2.0
create_directories: false
create_examples: true
native_tls: false
package: true
project_description: MCP server for Korea Meteorological Administration API access
project_name: kma-mcp
project_slug: kma_mcp
repo_url: https://github.com/appleparan/kma-mcp
version: 0.1.0

